---
title: "`r params$report_title`"
author: "`r params$report_author`"
date: "`r Sys.Date()`"
output: html_document
params:
  report_title: "Generate a simulated mortality dataset with single-age resolution"
  report_author: "Tamas Szabo"
knit: "(function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(dirname(inputFile)),'reports',paste(substr(basename(inputFile),1,nchar(basename(inputFile))-4),'_',Sys.Date(),'.html',sep=''))) })"
---

# Setup

## Library imports

```{r include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)

library(tidyr)
library(dplyr)
library(purrr)
library(openxlsx)

set.seed(25)
```

# Data parsing

## Population

```{r}
nat_population <- read.xlsx(
  "../example_data/A_továbbszámított_népesség_száma_népességnagyság-kategória_szerint (2).xlsx",
  startRow=7
)

colnames(nat_population) <- c("Period", "Sex", "Age", "Population")

nat_population <- nat_population %>%
  fill(Period, Sex) %>%
  mutate(
    Age = ifelse(Age == "1 éves kor alatt", "0", Age),
    Age = gsub(" .*", "", Age),
    Sex = ifelse(Sex == "Férfi", "Male", "Female"),
    Period = gsub("\\..*", "", Period)
  )
```

## Mortality

```{r}
pop_mort <- read.xlsx(
  "../example_data/Halálozás_vármegyék_és_jogállás_szerint (1).xlsx",
  startRow=7
)

colnames(pop_mort) <- c("Period", "Sex", "Age", "Diagnosis", "N_cases")

pop_mort <- pop_mort %>%
  fill(Period, Sex, Age) %>%
  mutate(
    Sex = ifelse(Sex == "Férfi", "Male", "Female"),
    Period = gsub("\\..*", "", Period),
    Diagnosis = ifelse(grepl("C18", Diagnosis), "Colorectal (C18)", "Lung (C33-34)"),
    N_cases = ifelse(is.na(N_cases), 1, N_cases)
  )
```

# Consolidation

## Emulating single-year precision



```{r}
empop_mort <- pop_mort %>%
  mutate(
    N_split_cases = map(
      N_cases,
      function(x) {
        y <- seq(1, 5)
        z <- table(sample(y, x, replace=TRUE))
        as.list(ifelse(y %in% names(z), z[as.character(y)], 0))
      }
    ),
    N_cases = map(
      N_cases,
      function(x) {
        list(a=x)
      }
    ),
    N_cases = ifelse(Age == "90-x", N_cases, N_split_cases)
  ) %>%
  select(-N_split_cases) %>%
  unnest(N_cases) %>%
  group_by(Period, Sex, Age, Diagnosis) %>%
  mutate(
    Age_small = seq(1, n()) - 1
  ) %>%
  ungroup() %>%
  mutate(
    Age = as.numeric(gsub("-.*", "", Age)),
    Age = Age + Age_small
  ) %>%
  select(-Age_small)
```

## Merged table

```{r}
main_tab <- nat_population %>%
  mutate(
    Age = ifelse(Age == "90-x", 90, Age),
    Age = as.numeric(Age)
  ) %>%
  left_join(empop_mort) %>%
  mutate(
    N_cases = ifelse(N_cases == "NULL", 0, N_cases),
    Diagnosis = map(
      Diagnosis,
      function(x) {
        if (is.na(x)) {
          list("Colorectal (C18)", "Lung (C33-34)")
        } else {
          list(a=x)
        }
      }
    )
  ) %>%
  unnest(Diagnosis) %>%
  mutate_all(as.character) %>%
  pivot_wider(names_from="Diagnosis", values_from=N_cases)
```

# Data export

## Save to csv

```{r}
write.csv(
  main_tab, "../example_data/crc_lung_mortality.csv",
  row.names=FALSE
)
```

# End