---
title: "`r params$report_title`"
author: "`r params$report_author`"
date: "`r Sys.Date()`"
output: html_document
params:
  report_title: "Showcase functionality of scripts in repo"
  report_author: "Tamas Szabo"
knit: "(function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(dirname(inputFile)),'reports',paste(substr(basename(inputFile),1,nchar(basename(inputFile))-4),'_',Sys.Date(),'.html',sep=''))) })"
---

# Setup

## Library imports

```{r include=FALSE, warning=FALSE, message=FALSE}

library(tidyr)
library(dplyr)
```

## Sourcing scripts

```{r}
source("../scripts/european_standard_population.R")
```

## Eaxample dataset

```{r}
example_dataset <- "../example_data/crc_lung_mortality.csv" %>%
  read.csv(check.names=FALSE) %>%
  pivot_longer(
    one_of("Colorectal (C18)", "Lung (C33-34)"),
    names_to = "Diagnosis", values_to = "N_cases"
  )

head(example_dataset)
```

```{r}
age_10_dataset <- example_dataset %>%
  mutate(
    Age_c = cut(Age, seq(-1, 100, 10)),
    Age_d = gsub(",.*", "", Age_c),
    Age_d = gsub("\\(", "", Age_d),
    Age_c = gsub(".*,", "", Age_c),
    Age_c = gsub("\\]", "", Age_c),
    Age = paste(as.numeric(Age_d)+1, "-", Age_c, sep=""),
    Age = ifelse(Age == "90-99", "90-x", Age)
  ) %>%
  group_by(Age, Sex, Period, Diagnosis) %>%
  summarise(
    Population = sum(Population),
    N_cases = sum(N_cases)
  ) %>%
  ungroup()
  

head(age_10_dataset)
```

# Functionality

## Standardized rates

```{r}
esp_2013_std_data <- age_10_dataset %>%
  rename(Raw_rate=N_cases, Year=Period) %>%
  left_join(get_esp_pop("2013", seq(0, 90, 10))) %>%
  add_standardized_rate("Raw_rate")
```

## Virtual patient numbers

## Average yearly change

## Expected case numbers

# End